---
#Install bind server and configure
- name: Load ubuntu variables
  include_vars: ubuntu.yml

- name: Install bind9 and utilities
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-dnsutils
    state: present
    update_cache: yes

- name: Configure named.conf.options (IPv4 only)
  copy:
    dest: /etc/bind/named.conf.options
    content: |
      options {
          directory "/var/cache/bind";
          recursion yes;
          allow-recursion { any; };
          forwarders {
              8.8.8.8;
              1.1.1.1;
          };
          dnssec-validation auto;
          // Listen only on IPv4:
          listen-on { any; };
          listen-on-v6 { any; };
      };
  notify: Restart Bind9

- name: Configure named.conf.local
  copy:
    dest: /etc/bind/named.conf.local
    content: |
      zone "{{ dns_domain }}" {
          type master;
          file "{{ dns_zone_file }}";
          update-policy {
            grant rndc-key zonesub any;
          };
      };
      zone "{{ dns_reverse_zone }}" {
          type master;
          file "{{ dns_reverse_zone_file }}";
          update-policy {
            grant rndc-key zonesub any;
          };
      };
  notify: Restart Bind9

- name: Create forward zone file
  copy:
    dest: "{{ dns_zone_file }}"
    owner: root
    group: bind
    mode: "0644"
    content: |
      $TTL 604800
      @       IN      SOA     ns1.{{ dns_domain }}. admin.{{ dns_domain }}. (
                          2         ; Serial
                          604800    ; Refresh
                          86400     ; Retry
                          2419200   ; Expire
                          604800 )  ; Negative Cache TTL
      ;
      @       IN      NS      ns1.{{ dns_domain }}.
      ns1     IN      A       {{ dns_network }}.2
      www     IN      A       {{ dns_network }}.2
      jenkins IN      A       {{ dns_network }}.2
      prometheus IN      A       {{ dns_network }}.101
  notify: Restart Bind9

- name: Create reverse zone file
  copy:
    dest: "{{ dns_reverse_zone_file }}"
    owner: root
    group: bind
    mode: "0644"
    content: |
      $TTL 604800
      @       IN      SOA     ns1.{{ dns_domain }}. admin.{{ dns_domain }}. (
                          2
                          604800
                          86400
                          2419200
                          604800 )
      @       IN      NS      ns1.{{ dns_domain }}.
      2      IN      PTR     ns1.{{ dns_domain }}.
      2      IN      PTR     www.{{ dns_domain }}.
      2      IN      PTR     jenkins.{{ dns_domain }}.
      101      IN      PTR     prometheus.{{ dns_domain }}.
  notify: Restart Bind9

- name: Check configuration syntax
  command: named-checkconf
  register: checkconf_out
  changed_when: false

- name: Check zone file syntax
  command: named-checkzone {{ dns_domain }} {{ dns_zone_file }}
  register: checkzone_out
  changed_when: false

- name: Ensure bind9 enabled and running
  systemd:
    name: bind9
    state: started
    enabled: true

...
