---
- name: Create Custom Unattended ISO
  hosts: localhost
  gather_facts: yes
  become: yes

  vars:
  # Define OS flavour and version
    #flavour: "ubuntu"
    #major_version: "24"
    #minor_version: "04.3"
    #version: "{{ major_version }}.{{ minor_version }}"
    #arch: "amd64"

  # Define OS flavour and version
    flavour: "rocky"
    major_version: "9"
    minor_version: "7"
    version: "{{ major_version }}.{{ minor_version }}"
    arch: "x86_64"

  # Common Variables
    network_ip: "192.168.122.46"
    network_cidr: "24"
    default_gateway: "192.168.122.1"
    boot_size: 2048  # 2GB
    swap_size: 2048  # 2GB

  tasks:
    - name: Set download iso_download_url
      set_fact:
        iso_download_url: >-
          {% if flavour == "ubuntu" %}
            https://releases.ubuntu.com/{{ version }}/
            ubuntu-{{ version }}-live-server-{{ arch }}.iso
          {% elif flavour == "debian" %}
            https://cdimage.debian.org/debian-cd/current/amd64/
            iso-cd/debian-{{ version }}-amd64-netinst.iso
          {% elif flavour == "redhat" %}
            https://access.redhat.com/downloads/content/69/ver=9/
            rhel---9/9.0/x86_64/product-software
          {% elif flavour == "centos" %}
            https://mirror.centos.org/centos/{{ major_version }}/
            isos/{{ arch }}/CentOS-{{ version }}-x86_64-minimal.iso
          {% elif flavour == "rocky" %}
            https://ftp.halifax.rwth-aachen.de/{{ flavour }}linux/
            {{ version }}/isos/{{ arch }}/
            Rocky-{{ version }}-{{ arch }}-minimal.iso
          {% else %}
            ""
          {% endif %}

    - name: Include role for ubuntu/debain custom iso creation
      include_role:
        name: ubuntu_create_custom_iso_unattended
      vars:
        working_dir: "/tmp/{{ flavour }}_{{ version }}_workdir"
        ansible_python_interpreter: /usr/bin/python3
        iso_mount_path: /mnt/iso
        iso_download_dest: "/tmp/{{ flavour }}_{{ version }}.iso"
        iso_output_path: >
          /var/www/html/isos/{{ flavour }}_{{ version }}_unattended.iso
        iso_extract_path: "{{ working_dir }}"
        default_user: "{{ flavour }}user"
        default_name: "{{ flavour }}user"
        defult_hostname: "{{ flavour }}-base"
        default_user_password: >
          $6$yyJVbiyTp2n5bHhp$XKIHL3VaMsl9RyqI0B9Ux3rW4lcwgEpeMjlNZH4/8YhF18LQ40om0ZH/n1Dy260aBPs1UrFz24L4T/oHFekSk.
        default_ssh_public_key: >
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOf3tJf45hHZFg/
          t96BnbQt8rHIQdQ/97o67XbgailYW suraj@HP-EliteBook
        boot_size: "{{ boot_size | default(2048) }}"  # 2GB
        swap_size: "{{ swap_size | default(2048) }}"  # 2GB
        default_timezone: "Europe/Berlin"
      when: flavour == "ubuntu" or flavour == "debian"

    - name: Include role for Redhat/Centos/Rocky custom iso creation
      include_role:
        name: redhat_create_custom_iso_unattended
      vars:
        working_dir: "/tmp/{{ flavour }}_{{ version }}_workdir"
        ansible_python_interpreter: /usr/bin/python3
        iso_mount_path: /mnt/iso
        iso_download_dest: >
          /tmp/{{ flavour }}_{{ version }}.iso
        iso_output_path: >
          /var/www/html/isos/{{ flavour }}_{{ version }}_unattended.iso
        iso_extract_path: "{{ working_dir }}"
        network_ip: "192.168.122.46"
        network_cidr: "24"
        default_gateway: "192.168.122.1"
        root_password: >
          $6$ieJsJXhSAf/QQC5t$05qbSBK.a0/KNGCHbcp7WoJIclkueKwNN0Afo/2v.ODjye.MvClRei596hm4bEsg.DteC4ECD1/Q0zAO0LGeY/
        default_user: "{{ flavour }}user"
        default_name: "{{ flavour }}user"
        defult_hostname: "{{ flavour }}-base"
        default_nameservers: "8.8.8.8,8.8.4.4"
        default_user_password: >
          $6$yyJVbiyTp2n5bHhp$XKIHL3VaMsl9RyqI0B9Ux3rW4lcwgEpeMjlNZH4/8YhF18LQ40om0ZH/n1Dy260aBPs1UrFz24L4T/oHFekSk.
        default_ssh_public_key: >
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOf3tJf45hHZFg/
          t96BnbQt8rHIQdQ/97o67XbgailYW suraj@HP-EliteBook
        boot_size: "{{ boot_size | default(2048) }}"  # 2GB
        swap_size: "{{ swap_size | default(2048) }}"  # 2GB
        default_timezone: "Europe/Berlin"
      when: flavour == "redhat" or flavour == "centos" or flavour == "rocky"

...
